// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sandbox.DataAccessLayer.Contexts;

#nullable disable

namespace Sandbox.DataAccessLayer.Migrations
{
    [DbContext(typeof(SandboxContext))]
    [Migration("20230927201028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Sandbox.DataAccessLayer.Models.SpearDbo", b =>
                {
                    b.Property<int>("SpearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Material")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpearmanDboSpearmanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpearId");

                    b.HasIndex("SpearmanDboSpearmanId");

                    b.ToTable("Spears");
                });

            modelBuilder.Entity("Sandbox.DataAccessLayer.Models.SpearmanDbo", b =>
                {
                    b.Property<int>("SpearmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpearmanId");

                    b.ToTable("SpearmanDbos");
                });

            modelBuilder.Entity("Sandbox.DataAccessLayer.Models.SpearDbo", b =>
                {
                    b.HasOne("Sandbox.DataAccessLayer.Models.SpearmanDbo", null)
                        .WithMany("Spears")
                        .HasForeignKey("SpearmanDboSpearmanId");
                });

            modelBuilder.Entity("Sandbox.DataAccessLayer.Models.SpearmanDbo", b =>
                {
                    b.Navigation("Spears");
                });
#pragma warning restore 612, 618
        }
    }
}
