// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sandbox.DataAccessLayer.Contexts;

#nullable disable

namespace Sandbox.DataAccessLayer.Migrations
{
    [DbContext(typeof(SandboxContext))]
    [Migration("20231003153913_RenameSpearmanTable")]
    partial class RenameSpearmanTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Sandbox.DataAccessLayer.Models.SpearDbo", b =>
                {
                    b.Property<int>("SpearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Material")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpearId");

                    b.ToTable("Spears");
                });

            modelBuilder.Entity("Sandbox.DataAccessLayer.Models.SpearmanDbo", b =>
                {
                    b.Property<int>("SpearmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpearmanId");

                    b.HasIndex("SpearId");

                    b.ToTable("Spearman");
                });

            modelBuilder.Entity("Sandbox.DataAccessLayer.Models.SpearmanDbo", b =>
                {
                    b.HasOne("Sandbox.DataAccessLayer.Models.SpearDbo", "Spear")
                        .WithMany()
                        .HasForeignKey("SpearId");

                    b.Navigation("Spear");
                });
#pragma warning restore 612, 618
        }
    }
}
